### ISSUE TITLE
Provider crashes while trying to create a report

### ISSUE THREAD

**Issue by haizaar** [doitintl/terraform-provider-doit-console#8]
I'm trying to create a report as defined here: https://github.com/doitintl/arbiter/blob/report-crash/finops/modules/playground-finops/reports.tf

The provider crashes unfortunately:

```
TF_LOG_PROVIDER=TRACE make tf-apply ARGS='--target=module.finops.module.sg-pod-1-cs.doit-console_report.playground_usage'
```
```
...
2023-11-16T00:17:06.043+1100 [DEBUG] provider.terraform-provider-doit-console_v0.1.4: 2023/11/16 00:17:06 hello report Create:)
2023-11-16T00:17:06.043+1100 [DEBUG] provider.terraform-provider-doit-console_v0.1.4: 2023/11/16 00:17:06 ***
2023-11-16T00:17:06.043+1100 [DEBUG] provider.terraform-provider-doit-console_v0.1.4: 2023/11/16 00:17:06 ---------------------------------------------------
2023-11-16T00:17:06.043+1100 [DEBUG] provider.terraform-provider-doit-console_v0.1.4: 2023/11/16 00:17:06 EE8CtpzYiKp0dVAESVrB
2023-11-16T00:17:06.043+1100 [DEBUG] provider.terraform-provider-doit-console_v0.1.4: 2023/11/16 00:17:06 before getting plan
2023-11-16T00:17:06.043+1100 [DEBUG] provider.terraform-provider-doit-console_v0.1.4: 2023/11/16 00:17:06 after getting plan
2023-11-16T00:17:06.043+1100 [TRACE] provider.terraform-provider-doit-console_v0.1.4: Served request: tf_proto_version=6.4 tf_provider_addr=registry.terraform.io/doitntl/doit-console @module=sdk.proto tf_req_id=99113e53-527d-f7d4-8910-fc889cba68fa tf_resource_type=doit-console_report tf_rpc=ApplyResourceChange @caller=runtime/panic.go:884 timestamp=2023-11-16T00:17:06.043+1100
2023-11-16T00:17:06.045+1100 [DEBUG] provider.terraform-provider-doit-console_v0.1.4: panic: runtime error: invalid memory address or nil pointer dereference
2023-11-16T00:17:06.045+1100 [DEBUG] provider.terraform-provider-doit-console_v0.1.4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x1 pc=0x7c56ed]
2023-11-16T00:17:06.045+1100 [DEBUG] provider.terraform-provider-doit-console_v0.1.4: 
2023-11-16T00:17:06.045+1100 [DEBUG] provider.terraform-provider-doit-console_v0.1.4: goroutine 83 [running]:
2023-11-16T00:17:06.045+1100 [DEBUG] provider.terraform-provider-doit-console_v0.1.4: terraform-provider-doit-console/internal/provider.(*reportResource).Create(0xc0000122e8, {0xce6da0, 0xc0002acc60}, {{{{0xceae28, 0xc0005b5560}, {0xae7d40, 0xc0002e8540}}, {0xcec270, 0xc000138870}}, {{{0xceae28, ...}, ...}, ...}, ...}, ...)
2023-11-16T00:17:06.045+1100 [DEBUG] provider.terraform-provider-doit-console_v0.1.4:   terraform-provider-doit-console/internal/provider/report_resource.go:528 +0x44d
2023-11-16T00:17:06.045+1100 [DEBUG] provider.terraform-provider-doit-console_v0.1.4: github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CreateResource(0xc000179ce0, {0xce6da0, 0xc0002acc60}, 0xc000295348, 0xc0002952e8)
2023-11-16T00:17:06.045+1100 [DEBUG] provider.terraform-provider-doit-console_v0.1.4:   github.com/hashicorp/terraform-plugin-framework@v1.4.0/internal/fwserver/server_createresource.go:101 +0x5b8
2023-11-16T00:17:06.045+1100 [DEBUG] provider.terraform-provider-doit-console_v0.1.4: github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0xce6da0?, {0xce6da0, 0xc0002acc60}, 0xc000240960, 0xc0002954b8)
2023-11-16T00:17:06.045+1100 [DEBUG] provider.terraform-provider-doit-console_v0.1.4:   github.com/hashicorp/terraform-plugin-framework@v1.4.0/internal/fwserver/server_applyresourcechange.go:57 +0x4a8
2023-11-16T00:17:06.045+1100 [DEBUG] provider.terraform-provider-doit-console_v0.1.4: github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0xc000179ce0, {0xce6da0?, 0xc0002acb10?}, 0xc000240910)
2023-11-16T00:17:06.045+1100 [DEBUG] provider.terraform-provider-doit-console_v0.1.4:   github.com/hashicorp/terraform-plugin-framework@v1.4.0/internal/proto6server/server_applyresourcechange.go:55 +0x27b
2023-11-16T00:17:06.045+1100 [DEBUG] provider.terraform-provider-doit-console_v0.1.4: github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc0001f4460, {0xce6da0?, 0xc0002ac150?}, 0xc00018c1c0)
2023-11-16T00:17:06.045+1100 [DEBUG] provider.terraform-provider-doit-console_v0.1.4:   github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov6/tf6server/server.go:857 +0x574
2023-11-16T00:17:06.045+1100 [DEBUG] provider.terraform-provider-doit-console_v0.1.4: github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0xb987c0?, 0xc0001f4460}, {0xce6da0, 0xc0002ac150}, 0xc00018c150, 0x0)
2023-11-16T00:17:06.045+1100 [DEBUG] provider.terraform-provider-doit-console_v0.1.4:   github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:467 +0x170
2023-11-16T00:17:06.045+1100 [DEBUG] provider.terraform-provider-doit-console_v0.1.4: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001e81e0, {0xceb158, 0xc0002129c0}, 0xc0002ab680, 0xc0003ce2a0, 0x1140238, 0x0)
2023-11-16T00:17:06.045+1100 [DEBUG] provider.terraform-provider-doit-console_v0.1.4:   google.golang.org/grpc@v1.57.1/server.go:1358 +0xe23
2023-11-16T00:17:06.045+1100 [DEBUG] provider.terraform-provider-doit-console_v0.1.4: google.golang.org/grpc.(*Server).handleStream(0xc0001e81e0, {0xceb158, 0xc0002129c0}, 0xc0002ab680, 0x0)
2023-11-16T00:17:06.045+1100 [DEBUG] provider.terraform-provider-doit-console_v0.1.4:   google.golang.org/grpc@v1.57.1/server.go:1735 +0xa2f
2023-11-16T00:17:06.045+1100 [DEBUG] provider.terraform-provider-doit-console_v0.1.4: google.golang.org/grpc.(*Server).serveStreams.func1.1()
2023-11-16T00:17:06.045+1100 [DEBUG] provider.terraform-provider-doit-console_v0.1.4:   google.golang.org/grpc@v1.57.1/server.go:970 +0xca
2023-11-16T00:17:06.045+1100 [DEBUG] provider.terraform-provider-doit-console_v0.1.4: created by google.golang.org/grpc.(*Server).serveStreams.func1
2023-11-16T00:17:06.045+1100 [DEBUG] provider.terraform-provider-doit-console_v0.1.4:   google.golang.org/grpc@v1.57.1/server.go:981 +0x15c
2023-11-16T00:17:06.046+1100 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/doitintl/doit-console/0.1.4/linux_amd64/terraform-provider-doit-console_v0.1.4 pid=834069 error="exit status 2"
2023-11-16T00:17:06.046+1100 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
╷
│ Warning: Resource targeting is in effect
│ 
│ You are creating a plan with the -target option, which means that the result of this plan may not represent all of the changes requested by the current configuration.
│ 
│ The -target option is not for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when Terraform specifically suggests to use it as part of an error message.
╵
╷
│ Warning: Applied changes may be incomplete
│ 
│ The plan was created with the -target option in effect, so some changes requested in the configuration may have been ignored and the output values may not be fully updated. Run the following command to verify that no other changes are pending:
│     terraform plan
│ 
│ Note that the -target option is not suitable for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when Terraform specifically suggests to use it as part of an error message.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-doit-console_v0.1.4 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1 pc=0x7c56ed]

goroutine 83 [running]:
terraform-provider-doit-console/internal/provider.(*reportResource).Create(0xc0000122e8, {0xce6da0, 0xc0002acc60}, {{{{0xceae28, 0xc0005b5560}, {0xae7d40, 0xc0002e8540}}, {0xcec270, 0xc000138870}}, {{{0xceae28, ...}, ...}, ...}, ...}, ...)
        terraform-provider-doit-console/internal/provider/report_resource.go:528 +0x44d
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CreateResource(0xc000179ce0, {0xce6da0, 0xc0002acc60}, 0xc000295348, 0xc0002952e8)
        github.com/hashicorp/terraform-plugin-framework@v1.4.0/internal/fwserver/server_createresource.go:101 +0x5b8
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0xce6da0?, {0xce6da0, 0xc0002acc60}, 0xc000240960, 0xc0002954b8)
        github.com/hashicorp/terraform-plugin-framework@v1.4.0/internal/fwserver/server_applyresourcechange.go:57 +0x4a8
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0xc000179ce0, {0xce6da0?, 0xc0002acb10?}, 0xc000240910)
        github.com/hashicorp/terraform-plugin-framework@v1.4.0/internal/proto6server/server_applyresourcechange.go:55 +0x27b
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc0001f4460, {0xce6da0?, 0xc0002ac150?}, 0xc00018c1c0)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov6/tf6server/server.go:857 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0xb987c0?, 0xc0001f4460}, {0xce6da0, 0xc0002ac150}, 0xc00018c150, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:467 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001e81e0, {0xceb158, 0xc0002129c0}, 0xc0002ab680, 0xc0003ce2a0, 0x1140238, 0x0)
        google.golang.org/grpc@v1.57.1/server.go:1358 +0xe23
google.golang.org/grpc.(*Server).handleStream(0xc0001e81e0, {0xceb158, 0xc0002129c0}, 0xc0002ab680, 0x0)
        google.golang.org/grpc@v1.57.1/server.go:1735 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.57.1/server.go:970 +0xca
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.57.1/server.go:981 +0x15c

Error: The terraform-provider-doit-console_v0.1.4 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

2023-11-16T00:17:06.546+1100 [DEBUG] provider: plugin exited
make: *** [Makefile:51: tf-apply] Error 1
```

**Comment by haizaar** [comment]
~~I think this happens when trying to reference non-existing report/attribution. But in anycase, the provider shouldn't crash.~~
Please disregard. The attributions exist and sound.

**Comment by dianibar** [comment]
I have fixed, but I want to do some additional test next week so I leave this open for now

**Comment by dianibar** [comment]
Fixed in the new repo https://github.com/doitintl/terraform-provider-doit that is used by the new  provider published https://registry.terraform.io/providers/doitintl/doit/latest
